# Generated by Django 3.2.5 on 2021-07-27 22:02

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField(null=True)),
                ('type', models.CharField(max_length=255, verbose_name='Item Type')),
                ('author', models.CharField(max_length=255, verbose_name='Item Author')),
                ('date_created', models.DateTimeField(null=True, verbose_name='Creation Time')),
                ('deleted', models.BooleanField(default=False, verbose_name='Is Item Deleted?')),
                ('dead', models.BooleanField(default=False, verbose_name='Is Item Dead?')),
                ('is_posted', models.BooleanField(default=False, verbose_name='Is Item Posted?')),
                ('kids', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), blank=True, null=True, size=None)),
                ('descendants', models.IntegerField(blank=True, null=True, verbose_name='Comment count')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='Item Score')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='Item url')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Item Title')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.IntegerField(blank=True, null=True, verbose_name='Comment Parent')),
                ('text', models.TextField(blank=True, max_length=255, verbose_name='Item Text')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_scrape.news', verbose_name='base news')),
            ],
        ),
    ]
