# Generated by Django 3.2.5 on 2021-07-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_scrape', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='item_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Item url'),
        ),
    ]
