# Generated by Django 3.2.5 on 2021-07-30 03:56

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news_scrape', '0003_alter_news_kids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='news',
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.CharField(default=1, max_length=255, verbose_name='Item Author'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='date_posted',
            field=models.DateTimeField(null=True, verbose_name='Creation Time'),
        ),
        migrations.AddField(
            model_name='comment',
            name='kids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='comment',
            name='type',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Item Type'),
            preserve_default=False,
        ),
    ]
