# Generated by Django 3.2.5 on 2021-07-30 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_scrape', '0004_auto_20210730_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True, default='', max_length=255, verbose_name='Item Text'),
        ),
    ]
