# Generated by Django 3.2.5 on 2021-07-30 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_scrape', '0006_alter_comment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Item Author'),
        ),
    ]
